exe: Abstractboard.class Array2D.class Array1D.class Test.class

Abstractboard.class: Abstractboard.java
	javac Abstractboard.java

Array2D.class: Array2D.java
	javac Array2D.java

Array1D.class: Array1D.java
	javac Array1D.java

Test.class: Test.java
	javac Test.java

clean: 
	rm *.class